// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Provide(arg1) {
  return window['go']['tagmanager']['TagManager']['Provide'](arg1);
}

export function SetContext(arg1) {
  return window['go']['tagmanager']['TagManager']['SetContext'](arg1);
}

export function TagSearch(arg1) {
  return window['go']['tagmanager']['TagManager']['TagSearch'](arg1);
}
