// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dbmanager} from '../models';
import {context} from '../models';
import {tagmanager} from '../models';

export function Provide(arg1:dbmanager.DatabaseManager):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TagSearch(arg1:tagmanager.TagSearchPayload):Promise<tagmanager.TagSearchResponse>;
