// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}
