// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assetmanager} from '../models';
import {vault} from '../models';
import {dbmanager} from '../models';
import {context} from '../models';

export function CreateAsset(arg1:string):Promise<assetmanager.CreateAssetResponse>;

export function CreateAssetFile(arg1:assetmanager.CreateAssetFilePayload):Promise<assetmanager.CreateAssetFileResponse>;

export function DeleteAssetFile(arg1:assetmanager.DeleteAssetFilePayload):Promise<assetmanager.DeleteAssetFileResponse>;

export function EditAssetFile(arg1:assetmanager.EditAssetFilePayload):Promise<assetmanager.EditAssetFileResponse>;

export function GetAsset(arg1:string):Promise<assetmanager.GetAssetResponse>;

export function ListAssetFiles(arg1:string,arg2:number):Promise<assetmanager.ListAssetFilesResponse>;

export function ListAssets():Promise<assetmanager.ListAssetsResponse>;

export function Provide(arg1:vault.Vault,arg2:dbmanager.DatabaseManager):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
