// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAsset(arg1) {
  return window['go']['assetmanager']['AssetManager']['CreateAsset'](arg1);
}

export function ListAssets() {
  return window['go']['assetmanager']['AssetManager']['ListAssets']();
}

export function Provide(arg1, arg2) {
  return window['go']['assetmanager']['AssetManager']['Provide'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['assetmanager']['AssetManager']['SetContext'](arg1);
}
